api_platform:
    title: 'API title'
    enable_re_doc: true
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    swagger:
        api_keys:
            apiKey:
                name: "X-AUTH-TOKEN"
                type: "header"