api_platform:
    title: 'Api ception'
    description: 'The API description'
    version: '1.0.0'
    doctrine:
        enabled: true
    formats:
        json:
            mime_types: ['application/json']
        html:
            mime_types: ['text/html']
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    swagger:
        api_keys:
            apiKey:
                name: "X-AUTH-TOKEN"
                type: "header"